apiVersion: v1
kind: Service
metadata:
  name: traffic-service-2  # 请替换{{instanceID}}为实际值
spec:
  selector:
    app: traffic-service-2 # 需与Deployment/Pod的标签匹配
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP