apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: confusionstrategies.cloudnative.example.com
spec:
  group: cloudnative.example.com
  names:
    kind: ConfusionStrategy
    listKind: ConfusionStrategyList
    plural: confusionstrategies
    singular: confusionstrategy
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                virtualServices:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      replicas:
                        type: integer
                      routes:
                        type: array
                        items:
                          type: object
                          properties:
                            target:
                              type: string
                            weight:
                              type: integer
                decoyLinks:
                  type: array
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                      destination:
                        type: string
                virtualLinks:
                  type: array
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                      destination:
                        type: string
