FROM golang:1.19-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod init traffic-generator && \
    go build -o traffic-generator

FROM alpine:3.16
WORKDIR /app
COPY --from=builder /app/traffic-generator .
EXPOSE 8080
CMD ["./traffic-generator"]