apiVersion: v1
kind: Service
metadata:
  name: traffic-service-{{ .INSTANCE_ID }}
spec:
  selector:
    app: traffic-generator-{{ .INSTANCE_ID }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP