apiVersion: v1
kind: Service
metadata:
  name: traffic-service-instance1
spec:
  selector:
    app: traffic-generator-instance1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP