FROM golang:1.24.1-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -ldflags="-s -w" -o obfuscation_agent

FROM alpine:3.16
WORKDIR /app
COPY --from=builder /app/obfuscation_agent .
EXPOSE 8080
CMD ["./obfuscation_agent"]